### PR TITLE
Delete event handling in the test

### PR DESCRIPTION
**Pull request by seppeljordan**
This 'feature' prevented automatic testing because it required user
interaction.

Some distros run the tests of a package to see if they pass.  The old version of the test required user input, which made it impossible/hard to install it on nisos for example.  I tweaked the test to not wait for user input.  Maybe we should think about a nice testsuite if we want test and move the old test program to a seprate program that does not get executed when `cabal test` is called.

### CODE REVIEW

**Comment by mankyKitty** [comment]
I think moving the file to a new location would be useful, probably an `examples` folder or equivalent. I am building a new-ish api for this library and I can include that in the changes.

Apologies but I haven't been using this library for a bit so there are still some rough edges. I do appreciate the help. :)

**Comment by seppeljordan** [comment]
Hey, i moved the old test to examples

**Comment by seppeljordan** [comment]
Okay, we have to pay attention to additional C sources because usually they don't get distributed.  I added the c code from the examples also to `additional-source-files`.

**Comment by mankyKitty** [comment]
They do seem to be a bit finicky, don't they. Thanks for the effort, I'll give this a spin and then merge it all up. :)

**Comment by seppeljordan** [comment]
Just let me know if something with this pull request got (more) broken.  I'd be happy to patch it up.

**Comment by mankyKitty** [comment]
Happy with this. :)

**Pull request merged**
